CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_resnet'
MODEL: 'multi_view_pose_transformer'
DATA_DIR: ''
GPUS: '0,1,2,3,4,5,6,7'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'shelf'
  TEST_DATASET: 'shelf'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  FLIP: False
  ROOT: 'data/Shelf'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX:
    - 2
    - 3
  CAMERA_NUM: 5
  PESUDO_GT: 'voxelpose_pesudo_gt_shelf.pickle'
NETWORK:
  PRETRAINED_BACKBONE: ''
  PRETRAINED:  ''
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 800
  - 608
  HEATMAP_SIZE:
  - 200
  - 152
  SIGMA: 3
  NUM_JOINTS: 15
  USE_GT: False
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 30
  RESUME: False
#  FINETUNE_MODEL: 'model_best_final.pth.tar'
  FINETUNE_MODEL: 'model_best_5view.pth.tar'
  OPTIMIZER: adam
  LR: 0.0002
TEST:
  MODEL_FILE: "model_best.pth.tar"
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
MULTI_PERSON:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2000.0
  SPACE_CENTER:
    - 450.0
    - -320.0
    - 800.0
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.1

DECODER:
  d_model: 256
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'relu'
  num_feature_levels: 1
  dec_n_points: 4
  num_decoder_layers: 6
  return_intermediate_dec: True
  num_instance: 10
  num_keypoints: 15
  with_pose_refine: True
  aux_loss: True
  lr_linear_proj_mult: 0.1
  loss_pose_normalize: False
  loss_joint_type: 'l1'
  pred_class_fuse: 'mean' # how to fuse the per joint class prediction, 'mean': train with per joint loss, eval with mean over the prediction
  pred_conf_threshold: 0.5
  match_coord: 'norm'
  detach_refpoints_cameraprj_firstlayer: True
  fuse_view_feats: 'cat_proj'

  optimizer: adamw
  lr_decay_epoch: 30
  query_embed_type: person_joint
  projattn_posembed_mode: use_rayconv
  loss_weight_loss_ce: 0.0
  inference_conf_thr: [0.0,]
  convert_joint_format_indices: [14, 13, 12, 6, 7, 8, 11, 10, 9, 3, 4, 5, 0, 1] # used for finetuning trained mvp on one dataset to another dataset (i.e., here panoptic to shelf/campus)